# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c318d04f5b5341131457cb7cc3ce1fff790dbde21980f7f58cd462e5ffa39d8970c0b7516c1832fdee5a45b576c63d9be80ebb48b41c03dcfdfb9521ec50fcf

test:
  secret_key_base: 0602975c386f956ffc289d19ea94d3b77b84266168357bf1242af744a80ff7192e01cb6b4555e25d062168adcaeebe5d6e5b1291c1dcff24a82721eedb51f87e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
